name: 'Back merge'

description: 'Merge specified branch to target'

inputs:
  from:
    description: 'From branch'
    required: true
  to:
    description: 'To branch'
    required: true
  gh_token:
    description: 'github token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set git config
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.from }}
        token: ${{ inputs.gh_token }}

    - name: Check specified branch
      shell: bash
      run: |
        git status
        git pull

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.to }}
        token: ${{ inputs.gh_token }}

    - name: Merge target branch
      shell: bash
      run: |
        git pull
        git merge origin/${{ inputs.from }} --ff
        git push
